image: openjdk:8-jdk

before_script: 
- export GRADLE_USER_HOME=cache/.gradle
- chmod +x ./gradlew
- rm -f  $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
- rm -fr $GRADLE_USER_HOME/caches/*/plugin-resolution/

cache:
  untracked: true
  paths:
  - cache/.gradle/wrapper
  - cache/.gradle/caches

compile:
  stage: build
  script: ./gradlew --no-daemon assemble
  artifacts:
    paths:
    - elki-bundle-*.jar
    expire_in: 1 week

test:
  stage: test
  script: ./gradlew --no-daemon check

